# Generated by Django 5.2.1 on 2025-05-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='groupmessage',
            old_name='auther',
            new_name='author',
        ),
    ]
