# Generated by Django 5.2.1 on 2025-05-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_groupmessage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='author',
            new_name='auther',
        ),
    ]
