# Generated by Django 5.2.1 on 2025-05-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_rename_author_groupmessage_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='auther',
            new_name='author',
        ),
    ]
