# Generated by Django 5.2.1 on 2025-05-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_rename_auther_groupmessage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.TextField(max_length=300),
        ),
    ]
